// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2sMobJSMOqHdDlpNS0IpfDWROfh700o',
    appId: '1:803582675466:web:2be48aafd724ab494c6df3',
    messagingSenderId: '803582675466',
    projectId: 'pcosproject-569e4',
    authDomain: 'pcosproject-569e4.firebaseapp.com',
    storageBucket: 'pcosproject-569e4.appspot.com',
    measurementId: 'G-SSWE8J1W71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTA3JeEvHhUWeQPPTfUlPF00FqTWPN4ns',
    appId: '1:803582675466:android:b15c5cb8f4b9426e4c6df3',
    messagingSenderId: '803582675466',
    projectId: 'pcosproject-569e4',
    storageBucket: 'pcosproject-569e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKhRX4GPRdxCLbB-9lmoTQD95QPoHiDg',
    appId: '1:803582675466:ios:e38aa1407d7c26454c6df3',
    messagingSenderId: '803582675466',
    projectId: 'pcosproject-569e4',
    storageBucket: 'pcosproject-569e4.appspot.com',
    iosClientId: '803582675466-cbosga4jj7me3mrc3lufal9lsfd6o5o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pcosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlKhRX4GPRdxCLbB-9lmoTQD95QPoHiDg',
    appId: '1:803582675466:ios:e38aa1407d7c26454c6df3',
    messagingSenderId: '803582675466',
    projectId: 'pcosproject-569e4',
    storageBucket: 'pcosproject-569e4.appspot.com',
    iosClientId: '803582675466-cbosga4jj7me3mrc3lufal9lsfd6o5o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pcosApp',
  );
}
